title: Jamie Berry # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: My name is Jamie Berry and I'm a graduate with a BSc (Hons) First Class in Games Design at Leeds Beckett University. I have been developing in Unity with C# and I have participated in Brains Eden 2017 and 2018. I would like to get an entry level job as a Gameplay Developer. I have worked on university projects and personal projects in both groups and individually.> # your text below (remove <br> elements if you don't need line breaks)
Game Developer
<br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
